version: '3'
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/usr/src/app
    env_file:
      - ./env/backend.env
    expose:
      - '3001'
    ports:
      - '3001:3001'
    command: npm run dev
    depends_on:
      - postgres
    restart: on-failure
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/usr/src/app
    env_file:
      - ./env/frontend.env
    expose:
      - '5173'
    ports:
      - '5173:5173'
    depends_on:
      - postgres
    restart: on-failure
  postgres:
    container_name: postgres
    image: "postgres:15-alpine"
    env_file:
      - ./env/postgres.env
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: on-failure
volumes:
  postgres:
