version: '3'
services:
  nginx: 
    build:
      context: ./nginx
    container_name: nginx
    image: 954587698208.dkr.ecr.eu-west-3.amazonaws.com/soccer-data-nginx
    ports: 
      - "80:80"
  backend: 
    build: 
      context: ./backend
    container_name: backend
    image: 954587698208.dkr.ecr.eu-west-3.amazonaws.com/soccer-data-backend
    ports: 
      - "3001:3001"
    environment:
      - JWT_SECRET=Ifta7ya5emSem
      - API_PORT=3001
      - DB_NAME=soccer_db
    command: node dist/server.js
  frontend: 
    build: 
      context: ./frontend
    container_name: frontend
    image: 954587698208.dkr.ecr.eu-west-3.amazonaws.com/soccer-data-frontend
    ports: 
      - "3000:3000"
