version: '3'
services:
  postgres:
    container_name: postgres
    image: "postgres:15-alpine"
    env_file:
      - ./env/postgres.env
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: on-failure
volumes:
  postgres:
